// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiT1letMRKyCD7T9fNHZ4HEGHlFBYHzoU',
    appId: '1:557528519034:web:3b64cb21acfec69fb1c6c3',
    messagingSenderId: '557528519034',
    projectId: 'loja-virtual-7df0c',
    authDomain: 'loja-virtual-7df0c.firebaseapp.com',
    storageBucket: 'loja-virtual-7df0c.appspot.com',
    measurementId: 'G-RV2XJ5F5RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1wdwPxXXHPLZXtQW-IU0jW3Pi0luBI40',
    appId: '1:557528519034:android:b401bb625291f55bb1c6c3',
    messagingSenderId: '557528519034',
    projectId: 'loja-virtual-7df0c',
    storageBucket: 'loja-virtual-7df0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeDohfRoiZO-gmeJoiTHWP8GB-dwrIZbo',
    appId: '1:557528519034:ios:de16baa5dcfef20db1c6c3',
    messagingSenderId: '557528519034',
    projectId: 'loja-virtual-7df0c',
    storageBucket: 'loja-virtual-7df0c.appspot.com',
    iosBundleId: 'com.example.lojaVirtual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeDohfRoiZO-gmeJoiTHWP8GB-dwrIZbo',
    appId: '1:557528519034:ios:de16baa5dcfef20db1c6c3',
    messagingSenderId: '557528519034',
    projectId: 'loja-virtual-7df0c',
    storageBucket: 'loja-virtual-7df0c.appspot.com',
    iosBundleId: 'com.example.lojaVirtual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiT1letMRKyCD7T9fNHZ4HEGHlFBYHzoU',
    appId: '1:557528519034:web:3b8f97ac0510ff90b1c6c3',
    messagingSenderId: '557528519034',
    projectId: 'loja-virtual-7df0c',
    authDomain: 'loja-virtual-7df0c.firebaseapp.com',
    storageBucket: 'loja-virtual-7df0c.appspot.com',
    measurementId: 'G-9VZMTWB6JL',
  );

}